[package]
name = "wait-for-them"
version = "0.2.0"
authors = ["Stepan Henek <stepan@henek.name>"]
edition = "2018"
description = "Waits for TCP ports to be opened"
license = "GPL-3.0"
readme = "README.md"
keywords = ["cli", "wait"]
repository = "https://github.com/shenek/wait-for-them"
categories = ["command-line-utilities"]

[features]
default = []
ui = ["indicatif"]

[dependencies]
futures = "0.3"
regex = "1"
tokio = {version="0.2", features=["tcp", "time", "process", "dns", "rt-threaded", "macros"]}
indicatif = {git="https://github.com/mibac138/indicatif", branch="mpb-tick", optional=true}

[dev-dependencies]
assert_cmd = "~0.12"

[[bin]]
name = "wait-for-them"
path = "src/main.rs"
